apiVersion: v1
kind: Service
metadata:
  name: helloworld-api
  labels:
    app: helloworld-api
spec:
  selector:
    app: helloworld-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
