apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: william-app-allow-gateway
  labels:
    app: william-app
spec:
  podSelector:
    matchLabels:
      app: william-app
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: envoy-gateway-system
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
