# Default values for helloworld-frontend. Overridden per environment by values/<tier>/<env>.yaml
replicaCount: 1

image:
  repository: nginxinc/nginx-unprivileged
  tag: latest

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

service:
  port: 80
  targetPort: 80
