{{- if index .Values "generic-service" "scheduledDowntime" "enabled" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduled-downtime-serviceaccount
  labels:
    app: hmpps-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scheduled-downtime-serviceaccount-role
  labels:
    app: hmpps-test
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["deployments/scale"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scheduled-downtime-serviceaccount-rolebinding
  labels:
    app: hmpps-test
subjects:
  - kind: ServiceAccount
    name: scheduled-downtime-serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scheduled-downtime-serviceaccount-role
{{- end }}