apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: myapp
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}-listenerset
      namespace: {{ .Values.gateway.namespace }}
      kind: ListenerSet
      group: gateway.networking.k8s.io
      sectionName: {{ .Values.gateway.sectionName }}
  hostnames:
    - {{ required "host must be configured" .Values.host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: myapp
          port: {{ .Values.service.port }}