# Default values for dan-testapp. Overridden per environment by values/<tier>/<env>.yaml
replicaCount: 1

image:
  repository: nginxinc/nginx-unprivileged
  tag: "1.27.4"
  digest: "sha256:663d1f83b634d625f3c36b323b21cc5c2c4ed5ebf912a01bfe13cce2f455e92e"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

service:
  port: 80
  targetPort: 8080