# Caller identity for the currently assumed role (used to detect plan/apply role)
data "aws_caller_identity" "current" {
}

locals {

  caller_identity        = data.aws_caller_identity.current
  environment_management = jsondecode(data.aws_secretsmanager_secret_version.environment_management.secret_string)
  caller_arn             = local.caller_identity.arn

  # Use administrator for apply runs and readonly for all other runs.
  is_identity_apply_role = can(regex("assumed-role/github-actions-container-platform-identity-apply/", local.caller_arn))

  sso_management_assume_role_name = local.is_identity_apply_role ? "ContainerPlatformSSOAdministrator" : "ContainerPlatformSSOReadOnly"

  # Aggregate all product manifests into a single map keyed by product name.
  # New schema: product.yaml with access[] at product level (not per-namespace).
  products = merge([
    for rel_path in fileset("${path.module}/../../namespaces", "**/product.yaml") : {
      (yamldecode(file("${path.module}/../../namespaces/${rel_path}")).product) = merge(
        yamldecode(file("${path.module}/../../namespaces/${rel_path}")),
        { source_file = rel_path }
      )
    }
  ]...)

  # List of all unique access groups across all products.
  # Each access entry has: group, role, clusters[]
  namespace_access_teams = toset(flatten([
    for product in values(local.products) : [
      for access_entry in try(product.access, []) : access_entry.group
    ]
  ]))

  # Static list of platform clusters for cp_user access assignments.
  namespace_clusters = toset([
    "container-platform-octo-nonlive",
    "container-platform-octo-live",
    "container-platform-hmpps-nonlive",
    "container-platform-hmpps-live",
    "container-platform-laa-nonlive",
    "container-platform-laa-live",
  ])

  # Map of team names to permission set names. The permission set names are generated by replacing spaces, underscores and dots with hyphens, and prefixing with "cp-".
  namespace_team_permission_set_names = {
    for team in local.namespace_access_teams :
    team => format("cp-%s", replace(replace(replace(lower(team), " ", "-"), "_", "-"), ".", "-"))
  }

  # List of all the unique combinations of team and cluster from product access[] entries.
  # Each access entry declares which clusters the group can access directly.
  namespace_team_cluster_keys = toset(flatten([
    for product in values(local.products) : [
      for access_entry in try(product.access, []) : [
        for cluster in access_entry.clusters : "${access_entry.group}|${cluster}"
      ]
    ]
  ]))

  # Map of team and cluster combinations to a map containing the team and cluster. This is used to create the account assignments for each team and cluster.
  namespace_team_cluster_assignments = {
    for key in local.namespace_team_cluster_keys :
    key => {
      team    = split("|", key)[0]
      cluster = split("|", key)[1]
    }
  }

  namespace_team_access_assignments = {
    for key, assignment in local.namespace_team_cluster_assignments :
    key => {
      cluster          = assignment.cluster
      target_id        = local.environment_management.account_ids[assignment.cluster]
      kubernetes_group = assignment.team
    }
  }

  namespace_team_access_assignments_octo_nonlive = {
    for key, assignment in local.namespace_team_access_assignments :
    key => assignment
    if assignment.cluster == "container-platform-octo-nonlive"
  }

  namespace_team_access_assignments_octo_live = {
    for key, assignment in local.namespace_team_access_assignments :
    key => assignment
    if assignment.cluster == "container-platform-octo-live"
  }

  namespace_team_access_assignments_hmpps_nonlive = {
    for key, assignment in local.namespace_team_access_assignments :
    key => assignment
    if assignment.cluster == "container-platform-hmpps-nonlive"
  }

  namespace_team_access_assignments_hmpps_live = {
    for key, assignment in local.namespace_team_access_assignments :
    key => assignment
    if assignment.cluster == "container-platform-hmpps-live"
  }

  namespace_team_access_assignments_laa_nonlive = {
    for key, assignment in local.namespace_team_access_assignments :
    key => assignment
    if assignment.cluster == "container-platform-laa-nonlive"
  }

  namespace_team_access_assignments_laa_live = {
    for key, assignment in local.namespace_team_access_assignments :
    key => assignment
    if assignment.cluster == "container-platform-laa-live"
  }

  cp_user_access_assignments = {
    for cluster in local.namespace_clusters :
    cluster => {
      cluster          = cluster
      target_id        = local.environment_management.account_ids[cluster]
      kubernetes_group = "cloud-platform-engineers"
    }
  }

  tags = {
    business-unit = "OCTO"
    service-area  = "Hosting"
    application   = "Container Platform"
    is-production = true
    owner         = "Cloud Platform: cloud-platform@justice.gov.uk"
  }
}
