# Caller identity for the currently assumed role (used to detect plan/apply role)
data "aws_caller_identity" "current" {
}

locals {

  caller_identity        = data.aws_caller_identity.current
  environment_management = jsondecode(data.aws_secretsmanager_secret_version.environment_management.secret_string)
  caller_arn             = local.caller_identity.arn

  # Use readonly for plan runs and administrator for apply runs.
  is_identity_plan_role  = can(regex("assumed-role/github-actions-container-platform-identity-plan/", local.caller_arn))
  is_identity_apply_role = can(regex("assumed-role/github-actions-container-platform-identity-apply/", local.caller_arn))

  sso_management_assume_role_name = local.is_identity_apply_role ? "ContainerPlatformSSOAdministrator" : "ContainerPlatformSSOReadOnly"

  # Aggregate all namespace manifests into a single map keyed by app name.
  namespaces = merge([
    for rel_path in fileset("${path.module}/../../namespaces", "**/namespace.yaml") : {
      (yamldecode(file("${path.module}/../../namespaces/${rel_path}")).name) = merge(
        yamldecode(file("${path.module}/../../namespaces/${rel_path}")),
        { source_file = rel_path }
      )
    }
  ]...)

  # List of all the teams that have access to any namespace in any environment, across all apps. This is used to create the permission sets and account assignments for each team.
  namespace_access_teams = toset(flatten([
    for app in values(local.namespaces) : flatten([
      for namespace in try(app.namespaces, []) : try(namespace.access, [])
    ])
  ]))

  # All unique cluster names referenced by namespace manifests.
  namespace_clusters = toset(flatten([
    for app in values(local.namespaces) : [
      for namespace in try(app.namespaces, []) : namespace.cluster
    ]
  ]))

  # Map of team names to permission set names. The permission set names are generated by replacing spaces, underscores and dots with hyphens, and prefixing with "cp-".
  namespace_team_permission_set_names = {
    for team in local.namespace_access_teams :
    team => format("cp-%s", replace(replace(replace(lower(team), " ", "-"), "_", "-"), ".", "-"))
  }

  # List of all the unique combinations of team and cluster that have access to any namespace in any environment, across all apps. This is used to create the account assignments for each team and cluster. 
  namespace_team_cluster_keys = toset(flatten(flatten([
    for app in values(local.namespaces) : [
      for namespace in try(app.namespaces, []) : [
        for team in try(namespace.access, []) : "${team}|${namespace.cluster}"
      ]
    ]
  ])))

  # Map of team and cluster combinations to a map containing the team and cluster. This is used to create the account assignments for each team and cluster.
  namespace_team_cluster_assignments = {
    for key in local.namespace_team_cluster_keys :
    key => {
      team    = split("|", key)[0]
      cluster = split("|", key)[1]
    }
  }

  namespace_team_access_assignments = {
    for key, assignment in local.namespace_team_cluster_assignments :
    key => {
      cluster          = assignment.cluster
      target_id        = local.environment_management.account_ids[assignment.cluster]
      kubernetes_group = assignment.team
    }
  }

  namespace_team_access_assignments_octo_nonlive = {
    for key, assignment in local.namespace_team_access_assignments :
    key => assignment
    if assignment.cluster == "container-platform-octo-nonlive"
  }

  namespace_team_access_assignments_octo_live = {
    for key, assignment in local.namespace_team_access_assignments :
    key => assignment
    if assignment.cluster == "container-platform-octo-live"
  }

  cp_user_cluster_keys = local.namespace_clusters

  cp_user_access_assignments = {
    for cluster in local.cp_user_cluster_keys :
    cluster => {
      cluster          = cluster
      target_id        = local.environment_management.account_ids[cluster]
      kubernetes_group = "cloud-platform-engineers"
    }
  }

  cp_user_access_assignments_octo_nonlive = {
    for key, assignment in local.cp_user_access_assignments :
    key => assignment
    if assignment.cluster == "container-platform-octo-nonlive"
  }

  cp_user_access_assignments_octo_live = {
    for key, assignment in local.cp_user_access_assignments :
    key => assignment
    if assignment.cluster == "container-platform-octo-live"
  }

  tags = {
    business-unit = "OCTO"
    service-area  = "Hosting"
    application   = "Container Platform"
    is-production = true
    owner         = "Cloud Platform: cloud-platform@justice.gov.uk"
  }
}
