apiVersion: apps/v1
kind: Deployment
metadata:
  name: dan-testapp
  labels:
    app: dan-testapp
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dan-testapp
  template:
    metadata:
      labels:
        app: dan-testapp
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: dan-testapp
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@{{ .Values.image.digest }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}