namespace: dns-testapp-dev
replicaCount: 1
host: dns-testapp.octo-nonlive.container-platform.service.justice.gov.uk
gateway:
  name: default
  namespace: envoy-gateway-system
tls:
  clusterIssuer: letsencrypt-staging