apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-frontend
  labels:
    app: helloworld-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: helloworld-frontend
  template:
    metadata:
      labels:
        app: helloworld-frontend
    spec:
      containers:
        - name: helloworld-frontend
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
