product: dns-testapp
bu: octo
owner:
  team: cloud-platform
  slack: "#cloud-platform"
  source: https://github.com/ministryofjustice/container-platform-environments
environments:
  - name: dev
    cluster: container-platform-octo-nonlive
    namespace: dns-testapp-dev
    is_production: false
access:
  - group: cloud-platform
    role: edit
    clusters:
      - container-platform-octo-nonlive