apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: dns-testapp
spec:
  parentRefs:
    - name: dns-testapp
      kind: ListenerSet
      group: gateway.networking.k8s.io
      sectionName: https
  hostnames:
    - {{ required "host must be configured" .Values.host | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: dns-testapp
          port: {{ .Values.service.port }}