name: Identity Plan

on:
  pull_request:
    paths:
      - "identity/terraform/**"
      - "identity/modules/**"
      - "namespaces/**/product.yaml"
      - ".github/workflows/identity-plan.yml"
  workflow_dispatch:

permissions: {}

jobs:
  plan:
    name: Identity Plan
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./identity/terraform
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
        with:
          role-to-assume: arn:aws:iam::${{secrets.CLOUD_PLATFORM_LIVE_ACCOUNT_ID}}:role/github-actions-container-platform-identity-plan
          role-session-name: GitHubActionsContainerPlatformIdentityPlan
          aws-region: eu-west-2
      - uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1
        with:
          terraform_version: 1.14.8
      - run: terraform init
      - run: terraform validate -no-color

      - name: Terraform plan
        id: plan
        run: |
          set -o pipefail
          terraform plan -detailed-exitcode | ../../scripts/redaction.sh